<a href="https://colab.research.google.com/github/Saptasindhu07/Random-Forests/blob/main/Random_Forest_Travel_Pro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) Problem statement.
"Trips & Travel.Com" company wants to enable and establish a viable business model to expand the customer base. One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering * Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information. The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being. However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.

#Content
What's inside is more than just rows and columns. Make it easy for others to get started by describing how you acquired the data and what time period it represents, too.

Most important features that have an impact on Product taken: Designation, Passport, Tier City, Martial status, occupation
Customers with Designation as Executive should be the target customers for the company .Customers who have passport and are from tier 3 city and are single or unmarried, have large business such customers have higher chances of taking new package.
Customers monthly income in range of 15000- 25000, and age range 15-30, prefer 5 star properties also have higher chances of taking new package based on EDA.
Inspiration
We need to analyze the customers' data and information to provide recommendations to the Policy Maker and Marketing Team and also build a model to predict the potential customer who is going to purchase the newly introduced travel package.

#Tasks to Solve :
To predict which customer is more likely to purchase the newly introduced travel package
Which variables are most significant.
Which segment of customers should be targeted more.

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("susant4learning/holiday-package-purchase-prediction")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/holiday-package-purchase-prediction

In [ ]:
import os
dataset_files = os.listdir(path)
print("Dataset files:", dataset_files)

Dataset files: ['Travel.csv']

In [ ]:
csv_file = os.path.join(path, 'Travel.csv')

In [ ]:
import pandas as pd
import numpy as np
data=pd.read_csv(csv_file)

In [ ]:
data

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

#Data Cleaning and Feature Engineering Steps

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [ ]:
data=data.dropna()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4128 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4128 non-null   int64
 1   ProdTaken                 4128 non-null   int64
 2   Age                       4128 non-null   float64
 3   TypeofContact             4128 non-null   object
 4   CityTier                  4128 non-null   int64
 5   DurationOfPitch           4128 non-null   float64
 6   Occupation                4128 non-null   object
 7   Gender                    4128 non-null   object
 8   NumberOfPersonVisiting    4128 non-null   int64
 9   NumberOfFollowups         4128 non-null   float64
 10  ProductPitched            4128 non-null   object
 11  PreferredPropertyStar     4128 non-null   float64
 12  MaritalStatus             4128 non-null   object
 13  NumberOfTrips             4128 non-null   float64
 14  Passport                  4128 non-null   int64
 15  PitchSatisfactionScore    4128 non-null   int64
 16  OwnCar                    4128 non-null   int64
 17  NumberOfChildrenVisiting  4128 non-null   float64
 18  Designation               4128 non-null   object
 19  MonthlyIncome             4128 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 677.2+ KB

In [ ]:
data['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       2918
Company Invited    1210
Name: count, dtype: int64

In [ ]:
data['CityTier'].value_counts()

CityTier
1    2678
3    1288
2     162
Name: count, dtype: int64

In [ ]:
data['Gender'].value_counts()

Gender
Male       2463
Female     1510
Fe Male     155
Name: count, dtype: int64

In [ ]:
data['Gender'].replace({'Fe Male':'Female'},inplace=True)

<ipython-input-387-4b3a04c47593>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Gender'].replace({'Fe Male':'Female'},inplace=True)
<ipython-input-387-4b3a04c47593>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Gender'].replace({'Fe Male':'Female'},inplace=True)

In [ ]:
data['Gender'].value_counts()

Gender
Male      2463
Female    1665
Name: count, dtype: int64

In [ ]:
data['ProductPitched'].value_counts()

ProductPitched
Basic           1615
Deluxe          1422
Standard         737
Super Deluxe     250
King             104
Name: count, dtype: int64

In [ ]:
data['PreferredPropertyStar'].value_counts()

PreferredPropertyStar
3.0    2541
5.0     801
4.0     786
Name: count, dtype: int64

In [ ]:
data['MaritalStatus'].value_counts()

MaritalStatus
Married      1990
Divorced      789
Unmarried     682
Single        667
Name: count, dtype: int64

In [ ]:
data['MaritalStatus'].replace({'Single':'Unmarried'},inplace=True)

<ipython-input-392-04c024f2741c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['MaritalStatus'].replace({'Single':'Unmarried'},inplace=True)
<ipython-input-392-04c024f2741c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['MaritalStatus'].replace({'Single':'Unmarried'},inplace=True)

In [ ]:
data['MaritalStatus'].value_counts()

MaritalStatus
Married      1990
Unmarried    1349
Divorced      789
Name: count, dtype: int64

In [ ]:
data['NumberOfTrips'].value_counts()

NumberOfTrips
2.0     1267
3.0      993
1.0      467
4.0      422
5.0      396
6.0      283
7.0      193
8.0      103
19.0       1
21.0       1
20.0       1
22.0       1
Name: count, dtype: int64

In [ ]:
data['Designation'].value_counts()

Designation
Executive         1615
Manager           1422
Senior Manager     737
AVP                250
VP                 104
Name: count, dtype: int64

In [ ]:
data.drop('CustomerID',axis=1,inplace=True)

<ipython-input-396-f615d0214e26>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('CustomerID',axis=1,inplace=True)

In [ ]:
data.drop('NumberOfChildrenVisiting', axis=1, inplace=True)

<ipython-input-397-14c03b2e8658>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('NumberOfChildrenVisiting', axis=1, inplace=True)

In [ ]:
data.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0
5,0,32.0,Company Invited,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Unmarried,1.0,0,5,1,Executive,18068.0

Extracting the Numeric and Categorical Features

In [ ]:
numeric_features= data.select_dtypes(include=np.number)
categorical_features=data.select_dtypes(exclude=np.number)

In [ ]:
numeric_features

,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,MonthlyIncome
0,1,41.0,3,6.0,3,3.0,3.0,1.0,1,2,1,20993.0
1,0,49.0,1,14.0,3,4.0,4.0,2.0,0,3,1,20130.0
2,1,37.0,1,8.0,3,4.0,3.0,7.0,1,3,0,17090.0
3,0,33.0,1,9.0,2,3.0,3.0,2.0,1,5,1,17909.0
5,0,32.0,1,8.0,3,3.0,3.0,1.0,0,5,1,18068.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4883,1,49.0,3,9.0,3,5.0,4.0,2.0,1,1,1,26576.0
4884,1,28.0,1,31.0,4,5.0,3.0,3.0,1,3,1,21212.0
4885,1,52.0,3,17.0,4,4.0,4.0,7.0,0,1,1,31820.0
4886,1,19.0,3,16.0,3,4.0,3.0,3.0,0,5,0,20289.0
4887,1,36.0,1,14.0,4,4.0,4.0,3.0,1,3,1,24041.0

In [ ]:
categorical_features

,TypeofContact,Occupation,Gender,ProductPitched,MaritalStatus,Designation
0,Self Enquiry,Salaried,Female,Deluxe,Unmarried,Manager
1,Company Invited,Salaried,Male,Deluxe,Divorced,Manager
2,Self Enquiry,Free Lancer,Male,Basic,Unmarried,Executive
3,Company Invited,Salaried,Female,Basic,Divorced,Executive
5,Company Invited,Salaried,Male,Basic,Unmarried,Executive
...,...,...,...,...,...,...
4883,Self Enquiry,Small Business,Male,Deluxe,Unmarried,Manager
4884,Company Invited,Salaried,Male,Basic,Unmarried,Executive
4885,Self Enquiry,Salaried,Female,Standard,Married,Senior Manager
4886,Self Enquiry,Small Business,Male,Basic,Unmarried,Executive
4887,Self Enquiry,Salaried,Male,Basic,Unmarried,Executive

Further splitting Numeric Features into Discrete and Continuous Features

In [ ]:
discrete_features=[feature for feature in numeric_features if len(data[feature].unique())<25]
continuous_features=[feature for feature in numeric_features if feature not in discrete_features]

In [ ]:
discrete_features=data[discrete_features]
continuous_features=data[continuous_features]

In [ ]:
discrete_features.head()

,ProdTaken,CityTier,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar
0,1,3,3,3.0,3.0,1.0,1,2,1
1,0,1,3,4.0,4.0,2.0,0,3,1
2,1,1,3,4.0,3.0,7.0,1,3,0
3,0,1,2,3.0,3.0,2.0,1,5,1
5,0,1,3,3.0,3.0,1.0,0,5,1

In [ ]:
continuous_features.head()

    Age  DurationOfPitch  MonthlyIncome
0  41.0              6.0        20993.0
1  49.0             14.0        20130.0
2  37.0              8.0        17090.0
3  33.0              9.0        17909.0
5  32.0              8.0        18068.0

#ENCODING THE CATEGORICAL FEATURE COLUMNS

We will use standard scaler on the continuous numerical columns.
We will use

In [ ]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, StandardScaler

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
continuous_features_copy=continuous_features.copy()
standard_scaler=StandardScaler()
continuous_features=standard_scaler.fit_transform(continuous_features)
continuous_features=pd.DataFrame(continuous_features,columns=continuous_features_copy.columns)

In [ ]:
continuous_features

           Age  DurationOfPitch  MonthlyIncome
0     0.410771        -1.141437      -0.485005
1     1.282857        -0.188730      -0.676524
2    -0.025272        -0.903260      -1.351170
3    -0.461315        -0.784172      -1.169415
4    -0.570326        -0.903260      -1.134129
...        ...              ...            ...
4123  1.282857        -0.784172       0.753991
4124 -1.006369         1.835773      -0.436403
4125  1.609889         0.168535       1.917755
4126 -1.987465         0.049447      -0.641238
4127 -0.134283        -0.188730       0.191416

[4128 rows x 3 columns]

In [ ]:
for col in categorical_features:
  categorical_features[col]=LabelEncoder().fit_transform(categorical_features[col])
categorical_features

,TypeofContact,Occupation,Gender,ProductPitched,MaritalStatus,Designation
0,1,2,0,1,2,2
1,0,2,1,1,0,2
2,1,0,1,0,2,1
3,0,2,0,0,0,1
5,0,2,1,0,2,1
...,...,...,...,...,...,...
4883,1,3,1,1,2,2
4884,0,2,1,0,2,1
4885,1,2,0,3,1,3
4886,1,3,1,0,2,1
4887,1,2,1,0,2,1

In [ ]:
df=pd.concat([categorical_features,discrete_features,continuous_features],axis=1)
df=df.loc[0:4127,:]
df.isnull().sum()

TypeofContact             0
Occupation                0
Gender                    0
ProductPitched            0
MaritalStatus             0
Designation               0
ProdTaken                 0
CityTier                  0
NumberOfPersonVisiting    0
NumberOfFollowups         0
PreferredPropertyStar     0
NumberOfTrips             0
Passport                  0
PitchSatisfactionScore    0
OwnCar                    0
Age                       0
DurationOfPitch           0
MonthlyIncome             0
dtype: int64

In [ ]:
df.head()

,TypeofContact,Occupation,Gender,ProductPitched,MaritalStatus,Designation,ProdTaken,CityTier,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Age,DurationOfPitch,MonthlyIncome
0,1.0,2.0,0.0,1.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,0.410771,-1.141437,-0.485005
1,0.0,2.0,1.0,1.0,0.0,2.0,0.0,1.0,3.0,4.0,4.0,2.0,0.0,3.0,1.0,1.282857,-0.188730,-0.676524
2,1.0,0.0,1.0,0.0,2.0,1.0,1.0,1.0,3.0,4.0,3.0,7.0,1.0,3.0,0.0,-0.025272,-0.903260,-1.351170
3,0.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,3.0,3.0,2.0,1.0,5.0,1.0,-0.461315,-0.784172,-1.169415
5,0.0,2.0,1.0,0.0,2.0,1.0,0.0,1.0,3.0,3.0,3.0,1.0,0.0,5.0,1.0,2.372964,-0.784172,-1.222455

In [ ]:
df.reset_index(drop=True)
df

,TypeofContact,Occupation,Gender,ProductPitched,MaritalStatus,Designation,ProdTaken,CityTier,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Age,DurationOfPitch,MonthlyIncome
0,1.0,2.0,0.0,1.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,0.410771,-1.141437,-0.485005
1,0.0,2.0,1.0,1.0,0.0,2.0,0.0,1.0,3.0,4.0,4.0,2.0,0.0,3.0,1.0,1.282857,-0.188730,-0.676524
2,1.0,0.0,1.0,0.0,2.0,1.0,1.0,1.0,3.0,4.0,3.0,7.0,1.0,3.0,0.0,-0.025272,-0.903260,-1.351170
3,0.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,3.0,3.0,2.0,1.0,5.0,1.0,-0.461315,-0.784172,-1.169415
5,0.0,2.0,1.0,0.0,2.0,1.0,0.0,1.0,3.0,3.0,3.0,1.0,0.0,5.0,1.0,2.372964,-0.784172,-1.222455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4123,1.0,3.0,1.0,3.0,1.0,3.0,0.0,1.0,4.0,4.0,5.0,2.0,0.0,1.0,0.0,1.282857,-0.784172,0.753991
4124,1.0,3.0,1.0,3.0,1.0,3.0,1.0,3.0,3.0,6.0,3.0,3.0,0.0,1.0,1.0,-1.006369,1.835773,-0.436403
4125,0.0,2.0,1.0,3.0,2.0,3.0,0.0,1.0,3.0,5.0,3.0,3.0,0.0,5.0,1.0,1.609889,0.168535,1.917755
4126,0.0,2.0,0.0,1.0,2.0,2.0,0.0,3.0,3.0,4.0,3.0,3.0,0.0,1.0,1.0,-1.987465,0.049447,-0.641238
4127,1.0,2.0,1.0,3.0,1.0,3.0,0.0,1.0,3.0,5.0,4.0,7.0,0.0,3.0,1.0,-0.134283,-0.188730,0.191416

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.drop('ProdTaken',axis=1),df['ProdTaken'],test_size=0.2)

In [ ]:
X_train

,TypeofContact,Occupation,Gender,ProductPitched,MaritalStatus,Designation,CityTier,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Age,DurationOfPitch,MonthlyIncome
3814,0.0,1.0,1.0,1.0,1.0,2.0,1.0,4.0,4.0,4.0,2.0,0.0,3.0,0.0,-0.461315,0.525801,-0.021630
1826,1.0,2.0,1.0,1.0,2.0,2.0,1.0,3.0,4.0,3.0,4.0,0.0,1.0,1.0,-0.025272,-1.022348,-0.378260
1385,1.0,3.0,1.0,3.0,1.0,3.0,3.0,2.0,3.0,3.0,2.0,0.0,1.0,1.0,1.282857,0.049447,2.327203
3144,1.0,1.0,1.0,0.0,2.0,1.0,1.0,3.0,4.0,3.0,6.0,0.0,2.0,1.0,-0.570326,0.168535,0.462162
747,1.0,2.0,1.0,1.0,2.0,2.0,3.0,2.0,3.0,3.0,1.0,1.0,3.0,1.0,1.609889,-0.545995,0.059372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1679,1.0,3.0,1.0,3.0,1.0,3.0,1.0,3.0,3.0,5.0,1.0,0.0,1.0,0.0,-0.134283,0.525801,-0.353404
1117,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,3.0,3.0,1.0,0.0,4.0,1.0,-0.570326,-1.141437,0.497892
1811,1.0,2.0,1.0,3.0,1.0,3.0,1.0,3.0,4.0,3.0,1.0,1.0,5.0,1.0,-0.352304,-0.069641,-0.546921
681,1.0,1.0,0.0,3.0,0.0,3.0,1.0,3.0,3.0,5.0,2.0,0.0,4.0,1.0,1.718899,-0.307818,2.314109
2027,0.0,2.0,0.0,1.0,1.0,2.0,1.0,3.0,3.0,5.0,3.0,0.0,4.0,1.0,-0.352304,1.597596,0.365182

In [ ]:
y_train

3814    0.0
1826    0.0
1385    0.0
3144    1.0
747     0.0
       ...
1679    0.0
1117    0.0
1811    0.0
681     0.0
2027    0.0
Name: ProdTaken, Length: 2758, dtype: float64

#Training our Random Forest Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score,precision_score,recall_score,f1_score

In [ ]:
models={
    'Logistic Regression':LogisticRegression(),
    'Decision Tree':DecisionTreeClassifier(),
    'Random Forest':RandomForestClassifier()
}

for i in range (len(list(models))):
  model=list(models.values())[i]
  model.fit(X_train,y_train)

  #Make Predictions
  y_train_pred=model.predict(X_train)
  y_test_pred=model.predict(X_test)

  #Test the Accuracy of the Model on Training Set
  model_train_accuracy=accuracy_score(y_train,y_train_pred)
  model_train_precision=precision_score(y_train,y_train_pred)
  model_train_recall=recall_score(y_train,y_train_pred)
  model_train_f1=f1_score(y_train,y_train_pred)

  #Test the Accuracy of the model on Testing Set
  model_test_accuracy=accuracy_score(y_test,y_test_pred)
  model_test_precision=precision_score(y_test,y_test_pred)
  model_test_recall=recall_score(y_test,y_test_pred)
  model_test_f1=f1_score(y_test,y_test_pred)

  print(list(models.keys())[i])
  print('Model Performance on Training Set')
  print('-Accuracy: {:.4f}'.format(model_train_accuracy))
  print('-Precision: {:.4f}'.format(model_train_precision))
  print('-Recall: {:.4f}'.format(model_train_recall))
  print('-F1 Score: {:.4f}'.format(model_train_f1))

  print('----------------------------------')

  print('Model Performance on Testing Set')
  print('-Accuracy: {:.4f}'.format(model_test_accuracy))
  print('-Precision: {:.4f}'.format(model_test_precision))
  print('-Recall: {:.4f}'.format(model_test_recall))
  print('-F1 Score: {:.4f}'.format(model_test_f1))
  print(classification_report(y_test,y_test_pred))
  print(confusion_matrix(y_test,y_test_pred))

  print('----------------------------------')

Logistic Regression
Model Performance on Training Set
-Accuracy: 0.8390
-Precision: 0.6519
-Recall: 0.2365
-F1 Score: 0.3471
----------------------------------
Model Performance on Testing Set
-Accuracy: 0.8449
-Precision: 0.6957
-Recall: 0.2560
-F1 Score: 0.3743
              precision    recall  f1-score   support

         0.0       0.86      0.98      0.91       565
         1.0       0.70      0.26      0.37       125

    accuracy                           0.84       690
   macro avg       0.78      0.62      0.64       690
weighted avg       0.83      0.84      0.81       690

[[551  14]
 [ 93  32]]
----------------------------------
Decision Tree
Model Performance on Training Set
-Accuracy: 1.0000
-Precision: 1.0000
-Recall: 1.0000
-F1 Score: 1.0000
----------------------------------
Model Performance on Testing Set
-Accuracy: 0.8014
-Precision: 0.4531
-Recall: 0.4640
-F1 Score: 0.4585
              precision    recall  f1-score   support

         0.0       0.88      0.88      0.88       565
         1.0       0.45      0.46      0.46       125

    accuracy                           0.80       690
   macro avg       0.67      0.67      0.67       690
weighted avg       0.80      0.80      0.80       690

[[495  70]
 [ 67  58]]
----------------------------------
Random Forest
Model Performance on Training Set
-Accuracy: 1.0000
-Precision: 1.0000
-Recall: 1.0000
-F1 Score: 1.0000
----------------------------------
Model Performance on Testing Set
-Accuracy: 0.8580
-Precision: 0.7077
-Recall: 0.3680
-F1 Score: 0.4842
              precision    recall  f1-score   support

         0.0       0.87      0.97      0.92       565
         1.0       0.71      0.37      0.48       125

    accuracy                           0.86       690
   macro avg       0.79      0.67      0.70       690
weighted avg       0.84      0.86      0.84       690

[[546  19]
 [ 79  46]]
----------------------------------

#Hyperparameter Tuning

In [ ]:
rf_params={
    'max_depth':[5,8,15,None,10,12,15,17],
    "max_features":[2,5,7,8,"auto"],
    "min_samples_leaf":[1,3,5,6,8,10],
    "n_estimators":[100,200,300,400]
}
rf_params

{'max_depth': [5, 8, 15, None, 10, 12, 15, 17],
 'max_features': [2, 5, 7, 8, 'auto'],
 'min_samples_leaf': [1, 3, 5, 6, 8, 10],
 'n_estimators': [100, 200, 300, 400]}

In [ ]:
randomvcModels=[
    ("RF",RandomForestClassifier(),rf_params)
]

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

model_param={}

for name,model,params in randomvcModels:
  random=RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=100,cv=5,verbose=2,n_jobs=-1,scoring='recall')


  random.fit(X_train,y_train)
  model_param[name]=random.best_params_

for model_name in model_param:
  print(f"Best Parameters for {model_name}: {model_param[model_name]}")

Fitting 5 folds for each of 100 candidates, totalling 500 fits

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
110 fits failed out of a total of 500.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.33877551 0.39795918        nan 0.17755102 0.22857143 0.30204082
 0.35714286 0.40612245 0.33877551        nan        nan 0.05918367
 0.15918367 0.33469388 0.16326531 0.4        0.06734694        nan
 0.34285714 0.31632653 0.18979592        nan 0.05714286 0.24285714
        nan 0.29591837 0.1        0.29387755 0.31428571 0.29591837
 0.34897959        nan 0.06734694        nan 0.20612245 0.3
 0.26326531 0.33265306 0.26734694 0.33877551 0.30408163        nan
 0.25306122 0.01020408 0.36326531 0.09591837 0.35102041 0.3
        nan        nan        nan 0.35714286 0.24897959 0.34081633
        nan        nan 0.14897959 0.35510204 0.26938776 0.33673469
 0.34897959 0.41020408 0.13673469 0.19183673 0.08979592 0.32653061
 0.23673469 0.29795918        nan 0.25918367 0.35306122 0.3755102
 0.31020408 0.34693878 0.33673469 0.35102041 0.0755102  0.24693878
 0.33265306 0.35510204        nan        nan 0.35102041 0.21020408
        nan 0.35306122        nan 0.35102041 0.28367347 0.28979592
 0.10816327 0.24489796 0.34897959        nan        nan 0.06530612
        nan 0.19387755 0.38163265 0.32040816]
  warnings.warn(

Best Parameters for RF: {'n_estimators': 300, 'min_samples_leaf': 1, 'max_features': 8, 'max_depth': 15}

In [ ]:
y_pred=random.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9608695652173913

In [ ]:
print(recall_score(y_test,y_pred))

0.832

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.96      0.99      0.98       565
         1.0       0.95      0.83      0.89       125

    accuracy                           0.96       690
   macro avg       0.95      0.91      0.93       690
weighted avg       0.96      0.96      0.96       690

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[559   6]
 [ 21 104]]

# **Satisfactory accuracy and performance of model**